# Generated by Django 2.2.13 on 2020-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('trader_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('mtz', models.PositiveIntegerField()),
                ('sell14', models.PositiveIntegerField()),
                ('sell7', models.PositiveIntegerField()),
                ('ost', models.PositiveIntegerField()),
                ('road', models.PositiveIntegerField()),
                ('summ', models.PositiveIntegerField()),
            ],
        ),
    ]
